---
- name: Create an empty dir and download jenkins.war into it
  hosts: all
  tasks:
    - name: Create a empty dir
      file:
        name: /tmp/dir1
        state: directory
    - name: Download jenkins.war into the above created directory
      get_url:
        url: https://get.jenkins.io/war-stable/2.504.3/jenkins.war
        dest: /tmp/dir1
...
