---
- name: Create user on all the servers
  hosts: dbserver
  tasks:
    - name: User creation
      user:
        name: Ramu
        password: intelliqit
        uid: 1357
        home: /tmp/Ramu
        shell: /bin/bash
        comment: "A normal user"
...
